//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirLines
    {
        public int Id { get; set; }
        public int PilotId { get; set; }
        public int ServiceStaffId { get; set; }
        public int PlaneId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Pilots Pilots { get; set; }
        public virtual Planes Planes { get; set; }
        public virtual ServiceStaff ServiceStaff { get; set; }
    }
}
