//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TinyAirLinesEntities : DbContext
    {
        public TinyAirLinesEntities()
            : base("name=TinyAirLinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirLines> AirLines { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Pilots> Pilots { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<ServiceStaff> ServiceStaff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
